import { db, hospitalsTable, doctorsTable, casesTable, transfersTable } from "@workspace/db";
import { count } from "drizzle-orm";

export async function initDb() {
  const [{ value: hospitalCount }] = await db.select({ value: count() }).from(hospitalsTable);

  if (Number(hospitalCount) > 0) {
    console.log(`[init-db] Database already seeded (${hospitalCount} hospitals found). Skipping.`);
    return;
  }

  console.log("[init-db] Database is empty — running initial seed...");

  // ── 1. Hospitals ─────────────────────────────────────────────────────────────
  const hospitals = await db.insert(hospitalsTable).values([
    {
      nameEn: "King Fahad Medical City",
      nameAr: "مدينة الملك فهد الطبية",
      city: "Riyadh",
      address: "Northern Ring Road, Riyadh 11525",
      phone: "+966-11-288-9999",
      specialties: ["Cardiology", "Neurology", "Oncology", "Emergency", "Pediatrics"],
      isAvailable: "true",
      level: "TERTIARY",
    },
    {
      nameEn: "King Abdullah Medical Complex",
      nameAr: "مجمع الملك عبدالله الطبي",
      city: "Jeddah",
      address: "Al Andalus District, Jeddah 23432",
      phone: "+966-12-629-0000",
      specialties: ["Orthopedics", "Internal Medicine", "Surgery", "Pulmonology"],
      isAvailable: "true",
      level: "TERTIARY",
    },
    {
      nameEn: "Prince Sultan Military Medical City",
      nameAr: "مدينة الأمير سلطان الطبية العسكرية",
      city: "Riyadh",
      address: "Wadi Al Dawasir, Riyadh 12233",
      phone: "+966-11-477-6666",
      specialties: ["Trauma", "Emergency", "Cardiology", "General Surgery"],
      isAvailable: "true",
      level: "TERTIARY",
    },
    {
      nameEn: "King Saud University Medical City",
      nameAr: "مدينة الملك سعود الطبية الجامعية",
      city: "Riyadh",
      address: "King Abdullah Road, Riyadh 11321",
      phone: "+966-11-467-0000",
      specialties: ["Neurology", "Psychiatry", "Dermatology", "Internal Medicine"],
      isAvailable: "true",
      level: "TERTIARY",
    },
    {
      nameEn: "Dhahran Health Center",
      nameAr: "مركز الظهران الصحي",
      city: "Dhahran",
      address: "Aramco District, Dhahran 31311",
      phone: "+966-13-872-0000",
      specialties: ["General Medicine", "Pediatrics", "Obstetrics"],
      isAvailable: "true",
      level: "SECONDARY",
    },
    // Hajjah–Sana'a referral pathway hospitals
    {
      nameEn: "Aahim Health Center",
      nameAr: "مركز عاهم الصحي",
      city: "كشر",
      address: "مديرية كشر، محافظة حجة",
      phone: "+967-7-000001",
      specialties: ["Primary Care", "Emergency First Aid", "رعاية أولية", "إسعاف أولي"],
      isAvailable: "true",
      level: "PRIMARY",
      pathwayOrder: 10,
      riskReduction: 5,
      distanceToNext: 40,
    },
    {
      nameEn: "Abs General Hospital",
      nameAr: "مستشفى عبس العام",
      city: "عبس",
      address: "مدينة عبس، محافظة حجة",
      phone: "+967-7-000002",
      specialties: ["Surgery", "Emergency", "Obstetrics", "جراحة", "طوارئ", "توليد"],
      isAvailable: "true",
      level: "SECONDARY",
      pathwayOrder: 11,
      riskReduction: 15,
      distanceToNext: 113,
    },
    {
      nameEn: "Hajjah Republican Hospital",
      nameAr: "هيئة مستشفى الجمهوري",
      city: "مدينة حجة",
      address: "مدينة حجة، محافظة حجة",
      phone: "+967-7-000003",
      specialties: ["Internal Medicine", "Pediatrics", "Cardiology", "باطنية", "أطفال", "قلبية"],
      isAvailable: "true",
      level: "SPECIALIZED",
      pathwayOrder: 12,
      riskReduction: 15,
      distanceToNext: 123,
    },
    {
      nameEn: "Kuwait University Hospital Sana'a",
      nameAr: "مستشفى جامعة الكويت — صنعاء",
      city: "صنعاء",
      address: "صنعاء، الجمهورية اليمنية",
      phone: "+967-1-000004",
      specialties: ["Neurosurgery", "Oncology", "Transplant", "ICU", "جراحة أعصاب", "أورام", "عناية مركزة"],
      isAvailable: "true",
      level: "TERTIARY",
      pathwayOrder: 13,
      riskReduction: 35,
      distanceToNext: 0,
    },
  ]).returning();

  const [hKFMC, hKAMC, hPSMM, hKSUMC, hDhahran, hAahim, hAbs, hHajjah, hSanaa] = hospitals;
  console.log(`[init-db] ✅ ${hospitals.length} hospitals seeded`);

  // ── 2. Doctors ────────────────────────────────────────────────────────────────
  const doctors = await db.insert(doctorsTable).values([
    {
      nameEn: "Dr. Ahmed Al-Rashidi", nameAr: "د. أحمد الراشدي",
      specialty: "CARDIOLOGY", specialtyLabelEn: "Cardiology", specialtyLabelAr: "أمراض القلب",
      qualifications: "MD, FACC — Board Certified Cardiologist",
      experience: 18, rating: "4.9", avatarInitials: "AR", isAvailable: true,
      consultationFeeUsd: "120.00", languages: ["Arabic", "English"],
    },
    {
      nameEn: "Dr. Sara Al-Otaibi", nameAr: "د. سارة العتيبي",
      specialty: "EMERGENCY_MEDICINE", specialtyLabelEn: "Emergency Medicine", specialtyLabelAr: "طب الطوارئ",
      qualifications: "MD, FAAEM — Emergency Medicine Specialist",
      experience: 12, rating: "4.7", avatarInitials: "SO", isAvailable: true,
      consultationFeeUsd: "100.00", languages: ["Arabic", "English"],
    },
    {
      nameEn: "Dr. Khalid Al-Ghamdi", nameAr: "د. خالد الغامدي",
      specialty: "NEUROLOGY", specialtyLabelEn: "Neurology", specialtyLabelAr: "طب الأعصاب",
      qualifications: "MD, PhD Neurology",
      experience: 20, rating: "4.8", avatarInitials: "KG", isAvailable: true,
      consultationFeeUsd: "150.00", languages: ["Arabic", "English"],
    },
    {
      nameEn: "Dr. Nora Al-Harbi", nameAr: "د. نورة الحربي",
      specialty: "INTERNAL_MEDICINE", specialtyLabelEn: "Internal Medicine", specialtyLabelAr: "الطب الباطني",
      qualifications: "MD, MRCP — Internal Medicine",
      experience: 15, rating: "4.6", avatarInitials: "NH", isAvailable: false,
      consultationFeeUsd: "90.00", languages: ["Arabic"],
    },
    {
      nameEn: "Dr. Faisal Al-Dossari", nameAr: "د. فيصل الدوسري",
      specialty: "SURGERY", specialtyLabelEn: "General Surgery", specialtyLabelAr: "الجراحة العامة",
      qualifications: "MD, FACS — General Surgery",
      experience: 22, rating: "4.9", avatarInitials: "FD", isAvailable: true,
      consultationFeeUsd: "200.00", languages: ["Arabic", "English"],
    },
    {
      nameEn: "Dr. Maha Al-Zahrani", nameAr: "د. مها الزهراني",
      specialty: "PEDIATRICS", specialtyLabelEn: "Pediatrics", specialtyLabelAr: "طب الأطفال",
      qualifications: "MD, Pediatric Specialist",
      experience: 10, rating: "4.5", avatarInitials: "MZ", isAvailable: true,
      consultationFeeUsd: "80.00", languages: ["Arabic", "English"],
    },
    {
      nameEn: "Dr. Omar Al-Shamri", nameAr: "د. عمر الشمري",
      specialty: "RADIOLOGY", specialtyLabelEn: "Radiology", specialtyLabelAr: "الأشعة",
      qualifications: "MD, Board Certified Radiologist",
      experience: 14, rating: "4.4", avatarInitials: "OS", isAvailable: true,
      consultationFeeUsd: "110.00", languages: ["Arabic", "English"],
    },
    {
      nameEn: "Dr. Reem Al-Mutairi", nameAr: "د. ريم المطيري",
      specialty: "OBSTETRICS", specialtyLabelEn: "Obstetrics & Gynecology", specialtyLabelAr: "أمراض النساء والتوليد",
      qualifications: "MD, OB/GYN Specialist",
      experience: 16, rating: "4.7", avatarInitials: "RM", isAvailable: false,
      consultationFeeUsd: "130.00", languages: ["Arabic", "English"],
    },
    // Yemeni doctors for Hajjah pathway
    {
      nameEn: "Dr. Yahya Al-Hajjah", nameAr: "د. يحيى الحجاوي",
      specialty: "EMERGENCY_MEDICINE", specialtyLabelEn: "Emergency Medicine", specialtyLabelAr: "طب الطوارئ",
      qualifications: "MBBS — طبيب طوارئ، مركز عاهم الصحي",
      experience: 6, rating: "4.3", avatarInitials: "YH", isAvailable: true,
      consultationFeeUsd: "40.00", languages: ["Arabic"],
    },
    {
      nameEn: "Dr. Samira Al-Absi", nameAr: "د. سميرة العبسية",
      specialty: "GENERAL", specialtyLabelEn: "General Medicine", specialtyLabelAr: "الطب العام",
      qualifications: "MBBS, Diploma Obstetrics — مستشفى عبس العام",
      experience: 9, rating: "4.5", avatarInitials: "SA", isAvailable: true,
      consultationFeeUsd: "50.00", languages: ["Arabic"],
    },
    {
      nameEn: "Dr. Faisal Al-Mutawakkil", nameAr: "د. فيصل المتوكل",
      specialty: "INTERNAL_MEDICINE", specialtyLabelEn: "Internal Medicine", specialtyLabelAr: "الطب الباطني",
      qualifications: "MD Internal Medicine — مستشفى الجمهوري حجة",
      experience: 12, rating: "4.6", avatarInitials: "FM", isAvailable: true,
      consultationFeeUsd: "65.00", languages: ["Arabic", "English"],
    },
    {
      nameEn: "Dr. Huda Al-Sanaa", nameAr: "د. هدى الصنعانية",
      specialty: "PEDIATRICS", specialtyLabelEn: "Pediatrics", specialtyLabelAr: "طب الأطفال",
      qualifications: "MD, MRCPCH — مستشفى جامعة الكويت صنعاء",
      experience: 15, rating: "4.8", avatarInitials: "HS", isAvailable: true,
      consultationFeeUsd: "90.00", languages: ["Arabic", "English"],
    },
    {
      nameEn: "Dr. Tariq Al-Hajjari", nameAr: "د. طارق الحجاري",
      specialty: "CARDIOLOGY", specialtyLabelEn: "Cardiology", specialtyLabelAr: "أمراض القلب",
      qualifications: "MD, Cardiology Fellowship — صنعاء",
      experience: 11, rating: "4.5", avatarInitials: "TH", isAvailable: true,
      consultationFeeUsd: "80.00", languages: ["Arabic"],
    },
    {
      nameEn: "Dr. Widad Al-Yemeni", nameAr: "د. وداد اليماني",
      specialty: "NEUROLOGY", specialtyLabelEn: "Neurology", specialtyLabelAr: "طب الأعصاب",
      qualifications: "MD Neurology — جامعة صنعاء",
      experience: 8, rating: "4.4", avatarInitials: "WY", isAvailable: false,
      consultationFeeUsd: "70.00", languages: ["Arabic"],
    },
  ]).returning();
  console.log(`[init-db] ✅ ${doctors.length} doctors seeded`);

  // ── 3. Demo Cases (non-Hajjah) ────────────────────────────────────────────────
  const demoCases = await db.insert(casesTable).values([
    {
      patientName: "Mohammed Al-Saeed",
      age: 62, gender: "MALE",
      chiefComplaint: "Chest pain radiating to left arm for 2 hours",
      symptoms: ["Chest pain", "Left arm pain", "Diaphoresis", "Shortness of breath"],
      vitalSigns: { heartRate: 105, bloodPressureSystolic: 165, bloodPressureDiastolic: 95, oxygenSaturation: 94, temperature: 37.1, respiratoryRate: 20 },
      medicalHistory: "Hypertension, Type 2 Diabetes",
      currentMedications: "Metformin 1000mg, Amlodipine 10mg",
      reportType: "SOAP",
      riskLevel: "CRITICAL",
      recommendedAction: "EMERGENCY_RESPONSE",
      riskFactors: ["Hypertension", "Diabetes", "Age > 60", "Classic STEMI presentation"],
      briefEnglish: "62M presenting with classic STEMI symptoms. Immediate cardiac catheterization required.",
      briefArabic: "مريض 62 عاماً بأعراض احتشاء عضلة القلب الكلاسيكية. يحتاج قسطرة قلبية فورية.",
      acknowledged: false,
      caseStatus: "CASE_CREATED",
      recommendedDepartment: "Emergency/Cardiology",
    },
    {
      patientName: "Fatima Bint Abdullah",
      age: 35, gender: "FEMALE",
      chiefComplaint: "Severe headache with photophobia for 6 hours",
      symptoms: ["Severe headache", "Photophobia", "Neck stiffness", "Vomiting"],
      vitalSigns: { heartRate: 88, bloodPressureSystolic: 140, bloodPressureDiastolic: 85, oxygenSaturation: 98, temperature: 38.8, respiratoryRate: 18 },
      medicalHistory: "Migraines (childhood)",
      currentMedications: "None",
      reportType: "SOAP",
      riskLevel: "HIGH",
      recommendedAction: "HOSPITAL_VISIT",
      riskFactors: ["Meningism signs", "Fever", "Sudden onset"],
      briefEnglish: "35F with meningeal signs. CT head and LP urgently required to rule out subarachnoid haemorrhage.",
      briefArabic: "أنثى 35 عاماً بعلامات سحائية. تحتاج CT وبزل قطني عاجلاً لاستبعاد نزيف تحت العنكبوتية.",
      acknowledged: true,
      caseStatus: "ASSIGNED_TO_DOCTOR",
      recommendedDepartment: "Neurology",
    },
    {
      patientName: "Khalid Bin Nasser",
      age: 45, gender: "MALE",
      chiefComplaint: "Diabetic foot ulcer with spreading redness",
      symptoms: ["Foot ulcer", "Redness", "Swelling", "Low grade fever"],
      vitalSigns: { heartRate: 92, bloodPressureSystolic: 130, bloodPressureDiastolic: 80, oxygenSaturation: 97, temperature: 37.9, respiratoryRate: 16 },
      medicalHistory: "Type 2 Diabetes (uncontrolled), Peripheral Arterial Disease",
      currentMedications: "Insulin glargine, Metformin",
      reportType: "SOAP",
      riskLevel: "HIGH",
      recommendedAction: "HOSPITAL_VISIT",
      riskFactors: ["Uncontrolled diabetes", "PAD", "Risk of amputation"],
      briefEnglish: "45M diabetic foot with cellulitis. IV antibiotics and urgent vascular review needed.",
      briefArabic: "مريض سكري 45 عاماً بقدم سكري مع التهاب نسيج خلوي. يحتاج مضادات حيوية IV ومراجعة وعائية.",
      acknowledged: true,
      caseStatus: "DIAGNOSIS_IN_PROGRESS",
      recommendedDepartment: "Vascular Surgery",
    },
    {
      patientName: "Aisha Al-Mansouri",
      age: 28, gender: "FEMALE",
      chiefComplaint: "Shortness of breath and wheezing",
      symptoms: ["Wheezing", "Dyspnoea", "Chest tightness", "Cough"],
      vitalSigns: { heartRate: 110, bloodPressureSystolic: 118, bloodPressureDiastolic: 75, oxygenSaturation: 92, temperature: 37.2, respiratoryRate: 26 },
      medicalHistory: "Asthma since childhood",
      currentMedications: "Salbutamol inhaler (PRN), Fluticasone",
      reportType: "SOAP",
      riskLevel: "HIGH",
      recommendedAction: "HOSPITAL_VISIT",
      riskFactors: ["Low SpO2", "High RR", "Known asthmatic"],
      briefEnglish: "28F acute severe asthma exacerbation. SpO2 92%, requires nebulisation and IV steroids.",
      briefArabic: "نوبة ربو حادة شديدة في أنثى 28 عاماً. SpO2 92٪، تحتاج بخاخات وستيرويد وريدي.",
      acknowledged: true,
      caseStatus: "RECEIVED_BY_HOSPITAL",
      recommendedDepartment: "Respiratory Medicine",
    },
    {
      patientName: "Ibrahim Al-Harthy",
      age: 70, gender: "MALE",
      chiefComplaint: "Confusion and fever since yesterday",
      symptoms: ["Confusion", "High fever", "Decreased urine output", "Weakness"],
      vitalSigns: { heartRate: 118, bloodPressureSystolic: 100, bloodPressureDiastolic: 60, oxygenSaturation: 95, temperature: 39.5, respiratoryRate: 24 },
      medicalHistory: "Benign Prostatic Hyperplasia, CKD stage 3",
      currentMedications: "Tamsulosin",
      reportType: "SOAP",
      riskLevel: "CRITICAL",
      recommendedAction: "EMERGENCY_RESPONSE",
      riskFactors: ["Sepsis criteria", "Altered consciousness", "CKD"],
      briefEnglish: "70M with sepsis criteria — likely urosepsis. Immediate blood cultures, broad-spectrum IV antibiotics, fluids.",
      briefArabic: "مريض 70 عاماً بمعايير إنتان — يُرجَّح إنتان بولي. زراعات دم فورية ومضادات حيوية واسعة الطيف.",
      acknowledged: false,
      caseStatus: "CASE_CREATED",
      recommendedDepartment: "Emergency/Urology",
    },
    {
      patientName: "Sara Al-Dosari",
      age: 52, gender: "FEMALE",
      chiefComplaint: "Right knee pain and swelling",
      symptoms: ["Knee pain", "Swelling", "Restricted movement", "Morning stiffness"],
      vitalSigns: { heartRate: 78, bloodPressureSystolic: 128, bloodPressureDiastolic: 82, oxygenSaturation: 98, temperature: 36.8, respiratoryRate: 14 },
      medicalHistory: "Osteoarthritis, Hypertension",
      currentMedications: "Paracetamol PRN, Lisinopril 10mg",
      reportType: "SOAP",
      riskLevel: "LOW",
      recommendedAction: "SCHEDULE_CONSULTATION",
      riskFactors: ["Age-related degeneration"],
      briefEnglish: "52F with right knee osteoarthritis flare. Outpatient orthopedic review and physiotherapy recommended.",
      briefArabic: "إناث 52 عاماً بنوبة تهيج في الركبة اليمنى. مراجعة خارجية للعظام والعلاج الطبيعي.",
      acknowledged: true,
      caseStatus: "COMPLETED",
      recommendedDepartment: "Orthopaedics",
      diagnosisNotes: "Osteoarthritis right knee — stage 3. Referred to physiotherapy. NSAID course started.",
    },
    {
      patientName: "Tariq Al-Balushi",
      age: 19, gender: "MALE",
      chiefComplaint: "Severe abdominal pain in RLQ",
      symptoms: ["RLQ pain", "Nausea", "Vomiting", "Rebound tenderness"],
      vitalSigns: { heartRate: 102, bloodPressureSystolic: 122, bloodPressureDiastolic: 78, oxygenSaturation: 99, temperature: 38.3, respiratoryRate: 17 },
      medicalHistory: "None",
      currentMedications: "None",
      reportType: "SOAP",
      riskLevel: "HIGH",
      recommendedAction: "HOSPITAL_VISIT",
      riskFactors: ["Rebound tenderness — peritoneal signs", "High WBC likely"],
      briefEnglish: "19M acute appendicitis. Urgent surgical review — risk of perforation if delayed.",
      briefArabic: "التهاب زائدة حادة في ذكر 19 عاماً. مراجعة جراحية عاجلة — خطر انثقاب في حال التأخير.",
      acknowledged: true,
      caseStatus: "ASSIGNED_TO_DOCTOR",
      recommendedDepartment: "General Surgery",
    },
    {
      patientName: "Maryam Al-Rashid",
      age: 31, gender: "FEMALE",
      chiefComplaint: "Panic attack with palpitations",
      symptoms: ["Palpitations", "Breathlessness", "Tingling fingers", "Fear"],
      vitalSigns: { heartRate: 130, bloodPressureSystolic: 145, bloodPressureDiastolic: 90, oxygenSaturation: 99, temperature: 36.9, respiratoryRate: 22 },
      medicalHistory: "Anxiety disorder",
      currentMedications: "Escitalopram 10mg",
      reportType: "SOAP",
      riskLevel: "MEDIUM",
      recommendedAction: "SCHEDULE_CONSULTATION",
      riskFactors: ["Tachycardia — needs ECG to exclude arrhythmia"],
      briefEnglish: "31F panic attack — ECG to exclude SVT. Reassurance and anxiolytic may suffice.",
      briefArabic: "نوبة هلع في أنثى 31 عاماً — ECG لاستبعاد SVT. طمأنة ومضاد قلق كافيان.",
      acknowledged: true,
      caseStatus: "ANALYZED",
      recommendedDepartment: "Psychiatry/Cardiology",
    },
    {
      patientName: "Hassan Al-Otaibi",
      age: 55, gender: "MALE",
      chiefComplaint: "Lower back pain after lifting",
      symptoms: ["Lower back pain", "Radiation to right leg", "Numbness"],
      vitalSigns: { heartRate: 76, bloodPressureSystolic: 132, bloodPressureDiastolic: 84, oxygenSaturation: 98, temperature: 36.7, respiratoryRate: 14 },
      medicalHistory: "Previous lumbar disc herniation (L4/L5)",
      currentMedications: "Diclofenac PRN",
      reportType: "SOAP",
      riskLevel: "MEDIUM",
      recommendedAction: "SCHEDULE_CONSULTATION",
      riskFactors: ["Sciatica — check for cauda equina signs"],
      briefEnglish: "55M acute lumbar disc herniation with right sciatica. MRI and neurosurgery referral advised.",
      briefArabic: "انزلاق غضروفي قطني حاد مع عرق النساء الأيمن في مريض 55 عاماً. MRI وإحالة جراحة أعصاب.",
      acknowledged: true,
      caseStatus: "REPORT_RECEIVED",
      recommendedDepartment: "Neurosurgery/Orthopaedics",
    },
    {
      patientName: "Nour Al-Jazeera",
      age: 6, gender: "FEMALE",
      chiefComplaint: "High fever and rash for 3 days",
      symptoms: ["High fever", "Rash", "Red eyes", "Swollen lymph nodes"],
      vitalSigns: { heartRate: 125, bloodPressureSystolic: 95, bloodPressureDiastolic: 60, oxygenSaturation: 97, temperature: 39.8, respiratoryRate: 28 },
      medicalHistory: "None",
      currentMedications: "Paracetamol",
      reportType: "SOAP",
      riskLevel: "HIGH",
      recommendedAction: "HOSPITAL_VISIT",
      riskFactors: ["Kawasaki criteria — risk of coronary aneurysm"],
      briefEnglish: "6F meeting Kawasaki criteria. IVIG and aspirin urgently needed — paediatric cardiology review.",
      briefArabic: "طفلة 6 سنوات بمعايير كاواساكي. IVIG وأسبرين عاجلان — مراجعة قلبية للأطفال.",
      acknowledged: false,
      caseStatus: "ROUTED_TO_HOSPITAL",
      recommendedDepartment: "Pediatric Cardiology",
    },
  ]).returning();
  console.log(`[init-db] ✅ ${demoCases.length} demo cases seeded`);

  // ── 4. Demo Transfers ─────────────────────────────────────────────────────────
  if (hKFMC && hKAMC && hPSMM && hDhahran) {
    await db.insert(transfersTable).values([
      {
        caseId: demoCases[0]?.id ?? null,
        direction: "OUTGOING",
        fromHospitalId: hDhahran.id,
        toHospitalId: hKFMC.id,
        patientName: "Mohammed Al-Saeed",
        patientAge: 62,
        patientGender: "MALE",
        chiefComplaint: "Chest pain radiating to left arm",
        riskLevel: "CRITICAL",
        transportMethod: "AMBULANCE",
        clinicalSummary: "STEMI — immediate cath lab activation needed at King Fahad Medical City.",
        status: "ACCEPTED",
        transferCode: "TRF-DEMO-001",
      },
      {
        caseId: demoCases[4]?.id ?? null,
        direction: "OUTGOING",
        fromHospitalId: hKAMC.id,
        toHospitalId: hPSMM.id,
        patientName: "Ibrahim Al-Harthy",
        patientAge: 70,
        patientGender: "MALE",
        chiefComplaint: "Sepsis — likely urosepsis",
        riskLevel: "CRITICAL",
        transportMethod: "AMBULANCE",
        clinicalSummary: "Urosepsis with hypotension and AKI. Transfer for ICU management.",
        status: "IN_TRANSIT",
        transferCode: "TRF-DEMO-002",
      },
      {
        caseId: demoCases[6]?.id ?? null,
        direction: "OUTGOING",
        fromHospitalId: hDhahran.id,
        toHospitalId: hKAMC.id,
        patientName: "Tariq Al-Balushi",
        patientAge: 19,
        patientGender: "MALE",
        chiefComplaint: "Acute appendicitis",
        riskLevel: "HIGH",
        transportMethod: "HOSPITAL_TRANSPORT",
        clinicalSummary: "Acute appendicitis — urgent laparoscopic appendicectomy.",
        status: "ARRIVED",
        transferCode: "TRF-DEMO-003",
      },
    ]);
  }

  // ── 5. Hajjah Clinical Cases ──────────────────────────────────────────────────
  if (hAahim && hAbs && hHajjah && hSanaa) {
    const hajjahCases = await db.insert(casesTable).values([
      {
        patientName: "علي حسين المطري",
        age: 58, gender: "MALE",
        chiefComplaint: "ألم شديد في الصدر مع تعرق وغثيان منذ ساعة",
        symptoms: ["ألم صدري حاد", "تعرق", "غثيان", "ضيق تنفس", "ألم في الذراع الأيسر"],
        vitalSigns: { heartRate: 112, bloodPressureSystolic: 185, bloodPressureDiastolic: 110, oxygenSaturation: 91, temperature: 37.2, respiratoryRate: 22 },
        medicalHistory: "ضغط دم مرتفع منذ 10 سنوات، غير منتظم في العلاج",
        currentMedications: "أملوديبين 5ملغ (غير منتظم)",
        reportType: "VOICE",
        riskLevel: "CRITICAL",
        recommendedAction: "EMERGENCY_RESPONSE",
        riskFactors: ["Critical symptom: chest pain", "Hypertensive crisis: 185/110 mmHg", "Hypoxia: SpO2 91%", "Tachycardia: 112 bpm", "Radiation to left arm — STEMI pattern"],
        briefEnglish: "HOSPITAL BRIEF — Risk Level: CRITICAL\n\nPatient: Ali Hussein Al-Matari, 58M. Crushing chest pain with radiation to left arm, onset 1 hour ago. HR 112, BP 185/110, SpO2 91%. History: uncontrolled hypertension.\n\nRecommended Action: IMMEDIATE EMERGENCY RESPONSE — Transfer to Abs General Hospital for cardiac intervention.",
        briefArabic: "ملخص طبي – مستوى الخطورة: حرج\n\nالمريض: علي حسين المطري، 58 عاماً ذكر. ألم صدري شديد بالتشتت للذراع الأيسر منذ ساعة. النبض 112، الضغط 185/110، الأكسجين 91٪. تاريخ: ضغط مرتفع غير منضبط.\n\nأسبرين 300ملغ في المركز، عاجل للتدخل القلبي.",
        acknowledged: false,
        caseStatus: "ROUTED_TO_HOSPITAL",
        recommendedDepartment: "Emergency Department",
      },
      {
        patientName: "فاطمة أحمد العوبلي",
        age: 26, gender: "FEMALE",
        chiefComplaint: "مخاض متعسر — الجنين في وضع مقعدي، نزيف مهبلي",
        symptoms: ["مخاض متعسر", "وضع مقعدي للجنين", "نزيف مهبلي", "ضائقة جنينية", "انخفاض ضغط الدم"],
        vitalSigns: { heartRate: 124, bloodPressureSystolic: 90, bloodPressureDiastolic: 58, oxygenSaturation: 96, temperature: 37.5, respiratoryRate: 24 },
        medicalHistory: "حمل أول، لا أمراض مزمنة",
        currentMedications: "حمض فوليك فقط",
        reportType: "VOICE",
        riskLevel: "HIGH",
        recommendedAction: "EMERGENCY_RESPONSE",
        riskFactors: ["Breech presentation", "Active hemorrhage", "Fetal distress: FHR 90 bpm", "Maternal hypotension"],
        briefEnglish: "Patient: Fatima Ahmed Al-Awbali, 26F, 38 weeks gestation. Obstructed labor — breech presentation with active hemorrhage. BP 90/58, HR 124, FHR 90 bpm — fetal distress. Emergency C-section required immediately.",
        briefArabic: "المريضة: فاطمة أحمد العوبلي، 26 أنثى، 38 أسبوع حمل. مخاض متعسر مع وضع مقعدي ونزيف نشط. ضغط 90/58، نبض 124، نبض جنيني 90 — ضائقة جنينية. قيصرية طارئة فورية.",
        acknowledged: false,
        caseStatus: "ASSIGNED_TO_DOCTOR",
        recommendedDepartment: "Obstetrics & Gynecology",
      },
      {
        patientName: "يوسف محمد الشمري",
        age: 4, gender: "MALE",
        chiefComplaint: "فشل تنفسي وشيك — ذات رئة حادة مع سوء تغذية",
        symptoms: ["ضيق تنفسي شديد", "حرارة مرتفعة جداً", "سرعة نبض", "سرعة تنفس", "زرقة", "ضعف عام"],
        vitalSigns: { heartRate: 156, bloodPressureSystolic: 88, bloodPressureDiastolic: 55, oxygenSaturation: 85, temperature: 40.1, respiratoryRate: 52 },
        medicalHistory: "سوء تغذية، لقاحات ناقصة",
        currentMedications: "لا يوجد",
        reportType: "VOICE",
        riskLevel: "CRITICAL",
        recommendedAction: "EMERGENCY_RESPONSE",
        riskFactors: ["Critical hypoxia: SpO2 85%", "Critically high temperature: 40.1°C", "Severe tachycardia: 156 bpm", "Tachypnea: RR 52/min", "Malnutrition — compromised immunity", "Incomplete vaccination"],
        briefEnglish: "4M child with acute pneumonia and impending respiratory failure. SpO2 85%, Temp 40.1°C, HR 156. Malnutrition and incomplete vaccinations. Needs specialist Paediatric ICU not available in Hajjah.",
        briefArabic: "طفل 4 سنوات مع ذات رئة حادة وفشل تنفسي وشيك. أكسجين 85٪، حرارة 40.1، نبض 156. سوء تغذية ولقاحات ناقصة. يحتاج وحدة عناية مركزة أطفال متخصصة غير متوفرة في حجة.",
        acknowledged: false,
        caseStatus: "ROUTED_TO_HOSPITAL",
        recommendedDepartment: "Pediatric ICU",
      },
      {
        patientName: "نجاة سعيد الوادعي",
        age: 45, gender: "FEMALE",
        chiefComplaint: "سكر مرتفع جداً مع غيبوبة جزئية",
        symptoms: ["غيبوبة جزئية", "سكر مرتفع", "جفاف شديد", "تنفس كيتوني"],
        vitalSigns: { heartRate: 108, bloodPressureSystolic: 105, bloodPressureDiastolic: 65, oxygenSaturation: 96, temperature: 37.8, respiratoryRate: 26 },
        medicalHistory: "سكري نوع 1 منذ 20 سنة",
        currentMedications: "أنسولين — انقطع عن الإمداد منذ أسبوعين",
        reportType: "VOICE",
        riskLevel: "HIGH",
        recommendedAction: "HOSPITAL_VISIT",
        riskFactors: ["DKA — Kussmaul breathing", "Altered consciousness", "Insulin supply interrupted"],
        briefEnglish: "45F Type 1 DM with DKA — Kussmaul breathing, partial coma. IV insulin, fluids, electrolytes urgent. Insulin supply disrupted by conflict.",
        briefArabic: "أنثى 45 بسكري نوع 1 وحماض كيتوني — تنفس كيتوني، غيبوبة جزئية. أنسولين وسوائل وريدية عاجلة. توقف إمداد الأنسولين بسبب الظروف.",
        acknowledged: true,
        caseStatus: "ASSIGNED_TO_DOCTOR",
        recommendedDepartment: "Internal Medicine",
      },
      {
        patientName: "عبدالرحمن محمد القيسي",
        age: 35, gender: "MALE",
        chiefComplaint: "إصابة بالغة بشظايا — بطن وصدر",
        symptoms: ["ألم شديد في البطن", "نزيف داخلي مشتبه", "صعوبة تنفس", "صدمة"],
        vitalSigns: { heartRate: 138, bloodPressureSystolic: 80, bloodPressureDiastolic: 50, oxygenSaturation: 88, temperature: 36.1, respiratoryRate: 32 },
        medicalHistory: "لا يوجد",
        currentMedications: "لا يوجد",
        reportType: "VOICE",
        riskLevel: "CRITICAL",
        recommendedAction: "EMERGENCY_RESPONSE",
        riskFactors: ["Haemodynamic shock", "Suspected internal haemorrhage", "Penetrating thoracoabdominal trauma", "Critical hypoxia"],
        briefEnglish: "35M penetrating thoracoabdominal trauma from shrapnel. BP 80/50, HR 138, SpO2 88% — haemodynamic shock. Emergency surgery required within 30 minutes.",
        briefArabic: "ذكر 35 بإصابة نافذة صدرية بطنية بشظايا. ضغط 80/50، نبض 138، أكسجين 88٪ — صدمة. جراحة طارئة خلال 30 دقيقة.",
        acknowledged: false,
        caseStatus: "CASE_CREATED",
        recommendedDepartment: "Emergency Surgery",
      },
      {
        patientName: "سلوى محمد الأصبحي",
        age: 48, gender: "FEMALE",
        chiefComplaint: "تسرع بطيني مع صدمة قلبية",
        symptoms: ["تسرع قلبي", "غياب شبه كامل للوعي", "ضغط منخفض جداً", "زرقة"],
        vitalSigns: { heartRate: 138, bloodPressureSystolic: 88, bloodPressureDiastolic: 54, oxygenSaturation: 90, temperature: 36.5, respiratoryRate: 28 },
        medicalHistory: "قصور قلبي معروف",
        currentMedications: "فوروسيميد، كارفيديلول",
        reportType: "VOICE",
        riskLevel: "CRITICAL",
        recommendedAction: "EMERGENCY_RESPONSE",
        riskFactors: ["Ventricular tachycardia with haemodynamic compromise", "Cardiogenic shock", "Known heart failure"],
        briefEnglish: "48F ventricular tachycardia with cardiogenic shock. Partial cardioversion in Hajjah. Needs full cardiac ICU and balloon pump.",
        briefArabic: "أنثى 48 بتسرع بطيني وصدمة قلبية. تحويل كهربائي جزئي في حجة. تحتاج وحدة قلب متكاملة ومضخة بالون.",
        acknowledged: false,
        caseStatus: "ROUTED_TO_HOSPITAL",
        recommendedDepartment: "Cardiac ICU",
      },
      {
        patientName: "حسن عبدالله القيسي",
        age: 67, gender: "MALE",
        chiefComplaint: "سكتة دماغية إقفارية حادة — NIHSS 16",
        symptoms: ["شلل نصفي", "اضطراب كلام", "شلل وجه", "انحراف نظر"],
        vitalSigns: { heartRate: 84, bloodPressureSystolic: 172, bloodPressureDiastolic: 102, oxygenSaturation: 96, temperature: 37.0, respiratoryRate: 16 },
        medicalHistory: "رجفان أذيني، ارتفاع ضغط",
        currentMedications: "وارفارين (غير منتظم)",
        reportType: "VOICE",
        riskLevel: "HIGH",
        recommendedAction: "EMERGENCY_RESPONSE",
        riskFactors: ["Large vessel occlusion — NIHSS 16", "Atrial fibrillation", "Hypertension", "Outside tPA window"],
        briefEnglish: "67M acute ischaemic stroke NIHSS 16. Right hemiplegia and aphasia. 3h onset — beyond tPA window in Hajjah. Needs thrombectomy evaluation in Sana'a.",
        briefArabic: "ذكر 67 بسكتة دماغية إقفارية حادة NIHSS 16. شلل نصفي أيمن وحبسة كلام. 3 ساعات — خارج نافذة tPA في حجة. يحتاج تقييم استخراج الجلطة في صنعاء.",
        acknowledged: true,
        caseStatus: "ROUTED_TO_HOSPITAL",
        recommendedDepartment: "Neurology/Interventional",
      },
      {
        patientName: "زهرة علي العرادة",
        age: 22, gender: "FEMALE",
        chiefComplaint: "حمى شديدة مع طفح جلدي نزفي",
        symptoms: ["حمى مرتفعة جداً", "طفح جلدي نزفي", "آلام مفصلية", "نزيف من اللثة"],
        vitalSigns: { heartRate: 118, bloodPressureSystolic: 95, bloodPressureDiastolic: 62, oxygenSaturation: 97, temperature: 40.3, respiratoryRate: 22 },
        medicalHistory: "لا يوجد",
        currentMedications: "لا يوجد",
        reportType: "VOICE",
        riskLevel: "HIGH",
        recommendedAction: "HOSPITAL_VISIT",
        riskFactors: ["Dengue haemorrhagic fever suspected", "Petechial rash — thrombocytopenia likely", "Bleeding signs"],
        briefEnglish: "22F dengue haemorrhagic fever — petechial rash, gum bleeding, thrombocytopenia suspected. Close monitoring and platelet transfusion readiness needed.",
        briefArabic: "أنثى 22 بحمى الضنك النزفية المشتبهة — طفح نزفي، نزيف لثوي، قلة صفيحات مشتبهة. مراقبة دقيقة وجهوزية نقل صفيحات.",
        acknowledged: false,
        caseStatus: "ANALYZED",
        recommendedDepartment: "Infectious Diseases",
      },
    ]).returning();
    console.log(`[init-db] ✅ ${hajjahCases.length} Hajjah cases seeded`);

    // ── 6. Hajjah Transfers ───────────────────────────────────────────────────────
    await db.insert(transfersTable).values([
      {
        caseId: hajjahCases[0]?.id ?? null,
        direction: "OUTGOING",
        fromHospitalId: hAahim.id,
        toHospitalId: hAbs.id,
        patientName: "علي حسين المطري",
        patientAge: 58, patientGender: "MALE",
        chiefComplaint: "ألم شديد في الصدر مع تعرق وغثيان منذ ساعة",
        riskLevel: "CRITICAL",
        status: "ARRIVED",
        transportMethod: "AMBULANCE",
        transferCode: "TRF-HAJ-0001",
        clinicalSummary: "STEMI مريض 58 سنة بألم صدري جاد مع تعرق، نبض 112، ضغط 185/110، أكسجين 91٪. أشنياء 300ملغ في المركز. عاجل للتدخل القلبي.",
        specialRequirements: "فريق طوارئ قلبية، مضاد التجلط جاهز، صدمة كهربائية متاحة",
        estimatedArrival: new Date("2026-03-16T10:30:00Z"),
      },
      {
        caseId: hajjahCases[2]?.id ?? null,
        direction: "OUTGOING",
        fromHospitalId: hHajjah.id,
        toHospitalId: hSanaa.id,
        patientName: "يوسف محمد الشمري",
        patientAge: 4, patientGender: "MALE",
        chiefComplaint: "فشل تنفسي وشيك — ذات رئة حادة مع سوء تغذية",
        riskLevel: "CRITICAL",
        status: "IN_TRANSIT",
        transportMethod: "AMBULANCE",
        transferCode: "TRF-HAJ-0002",
        clinicalSummary: "طفل 4 سنوات مع ذات رئة حادة وفشل تنفسي وشيك. أكسجين 85٪، حرارة 40.1، نبض 156. سوء تغذية ولقاحات ناقصة. يحتاج وحدة عناية مركزة أطفال متخصصة غير متوفرة في حجة.",
        specialRequirements: "سرير PICU، تنفس اصطناعي جاهز، مضادات حيوية IV مستمرة أثناء النقل",
        estimatedArrival: new Date("2026-03-16T14:00:00Z"),
      },
      {
        caseId: hajjahCases[6]?.id ?? null,
        direction: "OUTGOING",
        fromHospitalId: hHajjah.id,
        toHospitalId: hSanaa.id,
        patientName: "حسن عبدالله القيسي",
        patientAge: 67, patientGender: "MALE",
        chiefComplaint: "سكتة دماغية إقفارية حادة — NIHSS 16",
        riskLevel: "HIGH",
        status: "PENDING",
        transportMethod: "AMBULANCE",
        transferCode: "TRF-HAJ-0003",
        clinicalSummary: "مريض 67 سنة بشلل نصفي أيمن واضطراب كلام منذ 3 ساعات. NIHSS 16، ضغط 172/102، رجفان أذيني. يتجاوز نافذة tPA حجة — يحتاج تقييم استخراج الجلطة في صنعاء.",
        specialRequirements: "CT أنجيوغرافي عند الوصول، فريق تدخل عصبي، مضادات التخثر جاهزة",
        estimatedArrival: new Date("2026-03-16T16:00:00Z"),
      },
      {
        caseId: hajjahCases[5]?.id ?? null,
        direction: "INCOMING",
        fromHospitalId: hHajjah.id,
        toHospitalId: hSanaa.id,
        patientName: "سلوى محمد الأصبحي",
        patientAge: 48, patientGender: "FEMALE",
        chiefComplaint: "تسرع بطيني مع صدمة قلبية",
        riskLevel: "CRITICAL",
        status: "ACCEPTED",
        transportMethod: "AMBULANCE",
        transferCode: "TRF-HAJ-0004",
        clinicalSummary: "مريضة 48 سنة بتسرع بطيني وصدمة قلبية. نبض 138 غير منتظم، ضغط 88/54، أكسجين 90٪. تم تحويلها كهربائياً جزئياً في حجة. تحتاج وحدة قلب متكاملة وربما مضخة بالون.",
        specialRequirements: "وحدة قلب ICU، مضخة بالون داخل الأبهر، فريق تدخل قلبي",
        estimatedArrival: new Date("2026-03-16T09:00:00Z"),
      },
    ]);
    console.log(`[init-db] ✅ Hajjah transfers seeded`);
  }

  console.log("[init-db] ✅ Database initialized successfully.");
}
